### PR TITLE
Building the project's API v1

### PR DESCRIPTION
**Pull request by kevorks**
This PR aims to build our project's API. This includes several steps:

- One of the features, `National Cost (€)`, was causing some problems in defining the request body of the API. Therefore, this feature is renamed `NationalCost` to tackle this issue. This is handled in the `data_preprocessing.ipynb` notebook. This also implies new train and test data since the abovementioned feature is renamed.
- Train and test data are updated due to feature renaming. Since the train data was larger than accepted by GitHub; therefore, I needed to install `git lfs` to be able to upload the data.
- The model itself, namely the `pipe` object, is uploaded for later usage to get the predictions in the response body of the API.
- The API is built in the corresponding folder. To test the API, run the following command: `uvicorn main:app --reload`

If you have any questions, let us align tomorrow (Tuesday) before our scheduled meeting on Wednesday.

### CODE REVIEW

**Comment by kevorks** [comment]
You can use the following request body to play with API. Just to save you some time getting the real values from the data :)

{
  "HourOfCall": 0,
  "IncidentGroup": "Fire",
  "StopCodeDescription": "Primary Fire",
  "PropertyCategory": "Road Vehicle",
  "PropertyType": "House - single occupancy",
  "AddressQualifier": "Within same building",
  "ProperCase": "Ealing",
  "IncGeo_WardName": "WEST END",
  "NumStationsWithPumpsAttending": 2.0,
  "NumPumpsAttending": 3.0,
  "NumCalls": 4.0,
  "DateOfCall_Month": 6,
  "PartOfDay": "Night",
  "NationalCost": 2000.0
}

**Comment by mvigneron546** [comment]
Maybe it is just me but in the command `uvicorn main:app --reload` worked only when inside the `/api ` directory  (i.e. I need to `cd /api` to make it work) - is this also your experience?

More generally, we could start the different commands into the README.md, e.g.,

- `curl -X 'GET' http://127.0.0.1:8000/` for **health check**
- curl -X 'POST' \
  'http://127.0.0.1:8000/predict' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
"HourOfCall": 0,
"IncidentGroup": "Fire",
"StopCodeDescription": "Primary Fire",
"PropertyCategory": "Road Vehicle",
"PropertyType": "House - single occupancy",
"AddressQualifier": "Within same building",
"ProperCase": "Ealing",
"IncGeo_WardName": "WEST END",
"NumStationsWithPumpsAttending": 2.0,
"NumPumpsAttending": 3.0,
"NumCalls": 4.0,
"DateOfCall_Month": 6,
"PartOfDay": "Night",
"NationalCost": 2000.0
}' as an example

Furthermore, when testing with the following command (with the default input on the http://127.0.0.1:8000/docs page)
curl -X 'POST' \
  'http://127.0.0.1:8000/predict' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "HourOfCall": 0,
  "IncidentGroup": "string",
  "StopCodeDescription": "string",
  "PropertyCategory": "string",
  "PropertyType": "string",
  "AddressQualifier": "string",
  "ProperCase": "string",
  "IncGeo_WardName": "string",
  "NumStationsWithPumpsAttending": 0,
  "NumPumpsAttending": 0,
  "NumCalls": 0,
  "DateOfCall_Month": 0,
  "PartOfDay": "string",
  "NationalCost": 0
}', the API returns the following error (500, Internal Server Error), ValueError: NominalToIntegerTransformer: nulls would be introduced into column IncidentGroup from levels not present in mapping - this makes me think that we should start to make a list of data requirements to prevent this sort of faulty inputs into the API - any idea what causes this?

**Review by dbursy — APPROVED** [review]
As disucssed yesterday, the API works well on my side. 
Some remarks just to have them addressed:
- We can think about changing the prediction endpoint into a get request, but I think a post request makes the most sense since you have the option to store the data (for potential retraining at a later stage).
- How to start the API from the root directory will be explained in the ReadME

**Review by mvigneron546 — APPROVED** [review]
Thanks for the useful info @kevorks ! Considering that the objective here is to have a working API, this PR is good to go imo. 

Thanks for the great work!

**Pull request merged**
