### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by mvigneron546**
This PR attempts to save our issues with Azure authentication on Jenkins by creating a GitHub actions workflow. It works as follows:

- I set up different repository secrets to allow proper authentication to Azure on the GitHub workflow
- I translated the Jenkins file into an Actions file for a GitHub workflow. In addition the Azure authentication, it does exactly the same tasks already parameterized on the Jenkins file
- To fix issues related to pickle serialization, I had to change the format of train and test dataframes to parquet file. So far it works as intended.

The Docker files are untouched, this PR solely deals with CI/CD by using GitHub actions. Comments about the Docker containers should be addressed on this [PR](https://github.com/MLOpsGDA/mlops_fire_fighter/pull/5). 
Therefore, this branch will be merged to [jenkins-mlflow-docker-enhancement](https://github.com/MLOpsGDA/mlops_fire_fighter/tree/jenkins-mlflow-docker-enhancement), not `main`.

[Here](https://github.com/MLOpsGDA/mlops_fire_fighter/actions) is where you can find the worflowlogs.

@kevorks and @dbursy please review and add corrections/suggestions where you think necessary

### CODE REVIEW

**Comment by dbursy** [comment]
Add event triggered action and data collection, i.e., “At 00:00 on Sunday.”:

on:
  schedule:
    - cron: '0 0 * * 0'

    - name: 'Data Collection'
    - run: python3 -m utils.data_collection

See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by dbursy** [comment]
Hi Marc, in case you are facing issues with modeling.main.py
train = pd.read_pickle(file_path + '/train.parquet')
The function is misspecified -> read_parquet

**Comment by mvigneron546** [comment]
@kevorks @dbursy guys, in light of the fast approaching defense, may I suggest that we talk soon to agree on the road ahead? It is important that we agree quickly and what we do in the following weeks - Sebastien wants to already have a mock defense in 2 weeks...

@kevorks please let us know you are availabilities, it is important that those next steos are coordinated with you

**Review by dbursy — COMMENTED** [review]
GitHub Action file looks good, as discussed. CRON Job expected to work from main branch.

**Comment by mvigneron546** [comment]
I also added another worflow file to execute the retraining at predefined schedules - so far hitting a path issue with mlflow - but the overall idea works

**Pull request merged**
